db:
  image: mysql
  volumes:
    - /var/lib/mysql:/var/lib/mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=root

redis:
  image: redis
  volumes:
    - /var/lib/redis:/data
  environment:
    - ALLOW_EMPTY_PASSWORD=yes
  ports:
    - '6379:6379'

php:
  image: php:7.2.2-fpm
  volumes:
    #- /root/server-env/html:/var/www/html
    - /var/www/:/var/www/html
nginx:
  image: nginx
  ports:
    - "80:80"
  volumes:
    - /root/server-env/nginx:/etc/nginx/conf.d
    - /var/www/:/var/www/html
  links:
    - php:php
    - db:db
#web:
#  image: tutum/apache-php
#  ports:
#    - "80:80"
#  volumes:
#    - /var/www:/app
#  links:
#    - db:db