db:
  image: mysql
  volumes:
    - /var/lib/mysql:/var/lib/mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=root

redis:
  image: redis
  volumes:
    - /var/lib/redis:/data
  environment:
    - ALLOW_EMPTY_PASSWORD=yes
  ports:
    - '6379:6379'

web:
  image: tutum/apache-php
  ports:
    - "80:80"
  volumes:
    - /var/www:/app
  links:
    - db:db