db:
  image: mysql
  volumes:
    - /var/lib/mysql:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root

web:
  image: tutum/apache-php
  ports:
    - "80:80"
  volumes:
    - /var/www:/app
  links:
    - db:db